org: rjgallac
app: dynamo-test
service: dynamo-test

frameworkVersion: '3'

provider:
  name: aws
  region: eu-west-2
  runtime: nodejs14.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:eu-west-2:273521126402:table/TestTable

functions:
  hello:
    handler: handler.hello
  hello2:
    handler: handler.hello2
  hello3:
    handler: handler.hello3

resources:
  Resources:
    TodoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TestTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH